# Config file for automatic testing at travis-ci.org
# follows example from:
# http://conda.pydata.org/docs/travis.html
language: python
python:
    - "3.6"

# commands to set up conda
before_install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

# commands set up environment, install dependencies
install:
    - deps='pip beautifulsoup4 pymongo pandas pytest'
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
    - source activate test-environment
    - pip install python-coveralls
    - pip install .

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls
