channels: !!python/tuple
- !!python/unicode 'bioconda'
- !!python/unicode 'defaults'
dependencies:
- beautifulsoup4=4.5.1
- python-dateutil=2.7.3
- coverage=4.2
- funcsigs=1.0.2
- mkl=11.3.3
- mock
- numpy=1.11.2
- openssl
- pandas
- pbr=1.10.0
- pip
- py
- pymongo=3.3.0
- pytest
- pytest-cov=2.6.1
- python=3.6
- pytz=2019.3
- pyyaml=3.12
- zlib=1.2.8=3
- readline=6.2=2
- requests
- setuptools=27.2.0
- six=1.10.0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0
- yaml=0.1.6=0
- pip:
  - mongomock==3.6.0
  - sentinels==1.0.0
