channels: !!python/tuple
- !!python/unicode 'bioconda'
- !!python/unicode 'defaults'
dependencies:
- python=3.6
- beautifulsoup4=4.8.1
- biopython
- coverage
- funcsigs=1.0.2
- lxml
- matplotlib
- mkl
- mock
- numpy=1.17.4
- openssl
- pandas
- pbr=5.1.1
- pip
- py
- pymongo=3.9.0
- pytest
- pytest-cov=2.6.1
- python-dateutil=2.7.3
- pytz=2019.3
- pyyaml=3.12
- readline=7.0
- requests
- setuptools=42.0.2
- six=1.10.0
- sphinx=3.4.3
- sqlite=3.30.1
- tk=8.6.8
- wheel=0.29.0
- yaml=0.1.7
- zlib=1.2.11
- pip:
  - mongomock==3.6.0
  - sentinels==1.0.0
  - sphinx_rtd_theme==0.5.1