"""
Manages the collection and annotation of data (e.g., generated by the
Genomics Core or produced through bioinformatics processing) for import
into GenLIMS. Submodules are designed to handle the set of data
associated with a particular "step" (e.g., a flowcell sequencing run or
bioinformatics processing of a batch of samples). The ``dbify.control``
submodule inspects an input path and deplys the appropriate importer
class.
"""
from .sequencing import SequencingImporter
from .processing import ProcessingImporter
from .control import ImportManager
