"""
Manages the collection and annotation of data (e.g., generated by the
Genomics Core or produced through bioinformatics processing) for import
into GenLIMS. Modules are designed to handle the set of data
associated with a particular "step" (e.g., a flowcell sequencing run or
bioinformatics processing of a batch of samples). The ``dbify.control``
module inspects an input path and deploys the appropriate importer
class.
"""
from .flowcellrun import FlowcellRunImporter
from .workflowbatch import WorkflowBatchImporter
from .control import ImportManager
