"""
Contains class representations of various file types produced through
the generation or processing of genomics data. In particular, most of
these classes provide methods for reading and parsing raw data from
files and storing/returning these data in a more usable format, such
as dictionaries or data frames. Each submodule contains the
representaiton of a file generated by a particular tool or routine;
some submodules may handle files from multiple methods within a tool
(e.g., Picard). While not explicitly organized as such, submodules
adhere to a hierarchy based on the "type" of file, where current types
include metrics, counts, QC, and validation.
"""
from .workflowbatch import WorkflowBatchFile
from .picardmetrics import PicardMetricsFile
from .tophatstats import TophatStatsFile
from .htseqmetrics import HtseqMetricsFile
from .htseqcounts import HtseqCountsFile
from .fastqc import FastQCFile
from .sexcheck import SexcheckFile
