"""
Class for reading and parsing Picard metrics files.
"""
import logging
import re

from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)


class PicardMetricsFile(object):
    """
    Parser to read tables of metrics generated by one of several Picard tools,
    typically stored in an HTML file, and return as a parsed and formatted
    dictionary.
    """
    def __init__(self, path):
        self.path = path
        self.data = {}
        self._read_file()

    def _read_file(self):
        """
        Read file into raw HTML string.
        """
        logger.debug("reading file {} as to raw HTML string".format(self.path))
        with open(self.path) as f:
            self.data['raw'] = f.read()

    def _get_table(self):
        """
        Extract metrics table from raw HTML string.
        """
        raw_html = self.data['raw']
        soup = BeautifulSoup(raw_html, 'html.parser')
        logger.debug("getting metrics table from raw HTML string")
        return soup.findAll('table', attrs={'cellpadding': '3'})[0]

    def _check_table_format(self):
        """
        Check whether table is long (keys in one column, values in the other)
        or wide (keys in one row, values in the other).
        """
        table = self._get_table()
        if any([re.search(u'\xa0', td.text)
                for tr in table.findAll('tr')
                for td in tr.findAll('td')]):
            logger.debug("non-breaking space found in table; long format")
            return 'long'
        else:
            logger.debug("no non-breaking space found in table; wide format")
            return 'wide'

    def _parse_long(self):
        """
        Parse long-formatted table to dictionary.
        """
        table = self._get_table()
        metrics = {}
        for tr in table.findAll('tr'):
            for td in tr.findAll('td'):
                if re.search('^([A-Z]+(\_)*)+$', td.text):
                    td_key = td.text.replace('\n', '')
                    logger.debug("found metrics field {}".format(td_key))

                    td_val = td.next_sibling.string.replace(u'\xa0', u'')
                    td_val = td_val.replace('\n', '')
                    logger.debug("with corresponding value {}".format(td_val))

                    if len(td_val) and not re.search(r'[^\d.]+', td_val.lower()):
                        td_val = float(td_val)
                    metrics[td_key] = td_val
        logger.debug("parsed metrics table: {}".format(metrics))
        return metrics

    def _parse_wide(self):
        """
        Parse wide-formatted table to dictionary.
        """
        table = self._get_table()
        metrics = {}
        for tr in table.findAll('tr'):
            if re.search(u'\xa0', tr.text):
                return {}
            for td in tr.findAll('td'):
                if re.search('^[A-Z]+', td.text):
                    td_keys = td.text.split('\t')
                    logger.debug("found metrics fields: {}".format(td_keys))

                    td_vals = tr.next_sibling.next_sibling.text.split('\t')
                    logger.debug("found corresponding values: {}"
                                 .format(td_vals))

                    metrics_tmp = dict(zip(td_keys, td_vals))
                    metrics.update({k: float(v) if not re.search(r'[^\d.]+', v)
                                    else v
                                    for k, v in metrics_tmp.items()})
        logger.debug("parsed metrics table: {}".format(metrics))
        return metrics

    def parse(self):
        """
        Parse metrics table and return dictionary.
        """
        table_format = self._check_table_format()
        if table_format == 'long':
            return self._parse_long()
        else:
            return self._parse_wide()
